module.exports = {
  siteTitle: 'ASUC OCTO',
  siteTitleAlt: 'Business',
  siteLogo: '/logos/logo-512x512.png',
  siteUrl: 'https://http://asucocto.org/',
  pathPrefix: '/',
  siteDescription: 'UC Berkeley ASUC Office of the CTO',
  siteRss: '/rss.xml',
  siteFBAppID: '',
  googleTagManagerID: '',
  disqusShortname: '',
  userName: 'ASUC OCTO',
  userTwitter: '',
  userLocation: 'Berkeley, California',
  userDescription: '',
  copyright: 'Copyright © ASUC Office of the CTO 2018',
  themeColor: '#2e73f5',
  backgroundColor: '#ffffff',
};
